server {
    listen 80;
    root /usr/share/nginx/html;
    location / {
        add_header Access-Control-Allow-Origin * always;
        add_header Cache-Control "no-cache" always;
        try_files $uri $uri/ =404;
    }
}
